const express = require("express");
const groupRouter = express.Router();
const AppError = require("../utils/errors/AppError");
const { Group, Organizer, Event } = require("../models/setup");
// Base-url: /api/group

// Gets an req.query.organizer to filter
// Gets the group of events togheter with the events
// Example of response ( generated by gpt )
// [
//     {
//         "id": 1,
//         "name": "Group 1",
//         // ... other group fields
//         "Events": [
//             {
//                 "name": "Event 1",
//                 "description": "Description 1",
//                 "status": "active",
//                 "openDate": "2024-01-01"
//             },
//             // ... more events
//         ],
//         "Organizer": {
//             "name": "Organizer Name"
//         }
//     },
//     // ... more groups
// ]

groupRouter.get("/", async (req, res, next) => {
  try {
    if (!req.query.organizer) {
      throw new AppError("Organizer name is required", 400);
    }

    const groups = await Group.findAll({
      attributes: {
        exclude: ["modifiedAt"],
      },
      include: [
        {
          model: Event,
          attributes: ["name", "description", "status", "openDate"],
        },
        {
          model: Organizer,
          attributes: ["name"],
          where: {
            name: req.query.organizer,
          },
        },
      ],
    });

    if (!groups.length) {
      throw new AppError("No groups found for this organizer", 404);
    }

    res.json(groups);
  } catch (error) {
    next(error);
  }
});

module.exports = groupRouter;
